### ISSUE TITLE
NoSuchMethodError: android.adservices.customaudience.CustomAudienceManager.<init>(android.content.Context) after updating Facebook SDK to 18.0.X

### ISSUE THREAD

**Issue by lonskiTomasz** [facebook/facebook-android-sdk#1306]
### Checklist before submitting a bug report

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing [Github issues](https://github.com/facebook/facebook-android-sdk/issues)
- [x] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] This issue is not security related and can safely be disclosed publicly on GitHub

### Java version

21

### Android version

Not related

### Android SDK version

18.0.X

### Installation platform & version

Gradle (Android Gradle plugin 8.7.3)

### Package

Core & AppEvents

### Goals

- Successfully run UI snapshot tests using Paparazzi after upgrading the Facebook Android SDK from 17.0.0 to 18.0.X.

### Expected results

- The SDK should not invoke CustomAudienceManager when running in a JVM-only environment like Paparazzi.

### Actual results

- The Facebook SDK attempts to instantiate CustomAudienceManager even when running in a JVM-based test environment, causing NoSuchMethodError.
- This issue did not occur in v17.0.0, but appeared after upgrading to v18.0.X.

### Steps to reproduce

1. Upgrade Facebook SDK from 17.0.0 to 18.0.X
2. Run UI snapshot tests using Paparazzi
3. Observe the following crash:

> Cannot invoke "java.util.List.get(int)" because the return value of "com.android.ide.common.rendering.api.RenderSession.getRootViews()" is null
> java.lang.NullPointerException: Cannot invoke "java.util.List.get(int)" because the return value of "com.android.ide.common.rendering.api.RenderSession.getRootViews()" is null
> 	at app.cash.paparazzi.PaparazziSdk.takeSnapshots(PaparazziSdk.kt:245)
> 	at app.cash.paparazzi.PaparazziSdk.snapshot(PaparazziSdk.kt:178)
> 	at app.cash.paparazzi.PaparazziSdk.snapshot$default(PaparazziSdk.kt:176)
> 	at app.cash.paparazzi.PaparazziSdk.snapshot(PaparazziSdk.kt:173)
> 	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:103)
> 	at app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:100)

### Code samples & details

```java
// INSERT YOUR CODE HERE
```

**Comment by mrmike** [comment]
@lonskiTomasz, it seems that version 18.0.3 fixed the issue.
